In [2]:
import numpy as np 

## Data Types and Attributes

In [3]:
# Numpy main Data Type is ndarray 
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [9]:
# 1-Dimensional Array 
'''
Dimension : 1-Dimensional
Shape : (1,5)
Names :  Arrays and Vector
'''
a2=np.array([1,2,3,4,5])
a2

array([1, 2, 3, 4, 5])

In [10]:
# 2-Dimensional Array 
'''
Dimension : 2-Dimensional 
Shape : (3,3)
Names : Arrays and Matrix
'''
a3=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# 3-Dimensional Array 
'''
Dimension : 3-Dimensional 
Shape : (2,3,2)
Names : Arrays and Matrix
'''
a4=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
print('a2 shape : ',end=' ')
print(a2.shape)

a2 shape :  (5,)


In [20]:
print('a3 shape : ',end=' ')
print(a3.shape)

a3 shape :  (3, 3)


In [21]:
print('a4 shape : ',end=' ')
print(a4.shape)

a4 shape :  (2, 3, 3)


In [22]:
a2.ndim , a3.ndim , a4.ndim

(1, 2, 3)

In [25]:
a2.dtype , a3.dtype , a4.dtype 

(dtype('int32'), dtype('int32'), dtype('int32'))

In [27]:
a2.size , a3.size , a4.size

(5, 9, 18)

In [28]:
type(a1) , type(a3) , type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [33]:
# Creating DataFrame from Numpy Arrays 
import pandas as pd 

df1=pd.DataFrame(a3)
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9