In [1]:
import numpy as np 

## Data Types and Attributes

In [2]:
# Numpy main Data Type is ndarray 
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
# 1-Dimensional Array 
'''
Dimension : 1-Dimensional
Shape : (1,5)
Names :  Arrays and Vector
'''
a2=np.array([1,2,3,4,5])
a2

array([1, 2, 3, 4, 5])

In [5]:
# 2-Dimensional Array 
'''
Dimension : 2-Dimensional 
Shape : (3,3)
Names : Arrays and Matrix
'''
a3=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# 3-Dimensional Array 
'''
Dimension : 3-Dimensional 
Shape : (2,3,2)
Names : Arrays and Matrix
'''
a4=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
print('a2 shape : ',end=' ')
print(a2.shape)

a2 shape :  (5,)


In [8]:
print('a3 shape : ',end=' ')
print(a3.shape)

a3 shape :  (3, 3)


In [9]:
print('a4 shape : ',end=' ')
print(a4.shape)

a4 shape :  (2, 3, 3)


In [10]:
a2.ndim , a3.ndim , a4.ndim

(1, 2, 3)

In [11]:
a2.dtype , a3.dtype , a4.dtype 

(dtype('int32'), dtype('int32'), dtype('int32'))

In [12]:
a2.size , a3.size , a4.size

(5, 9, 18)

In [13]:
type(a1) , type(a3) , type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Creating DataFrame from Numpy Arrays 
import pandas as pd 

df1=pd.DataFrame(a3)
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Creating Numpy Arrays 

In [15]:
sample_arr=np.array([1,2,3])
sample_arr

array([1, 2, 3])

In [16]:
sample_arr.dtype

dtype('int32')

In [17]:
one_arr=np.ones((2,3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
one_arr.dtype

dtype('float64')

In [19]:
type(one_arr)

numpy.ndarray

In [20]:
zero_arr=np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_arr=np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [22]:
rand_arr=np.random.randint(3,10,size=(2,3))
rand_arr

array([[5, 3, 5],
       [9, 6, 6]])

In [23]:
rand_arr.size 


6

In [24]:
rand_arr.shape

(2, 3)

In [25]:
rand_arr2=np.random.random((3,4))
rand_arr2

array([[0.45912491, 0.65198105, 0.05838949, 0.29560705],
       [0.02270458, 0.38648705, 0.33053404, 0.6179213 ],
       [0.95590158, 0.80922586, 0.5200838 , 0.00238096]])

In [26]:
rand_arr2.shape

(3, 4)

In [27]:
rand_arr2.size

12

In [28]:
rand_arr3=np.random.rand(2,3)
rand_arr3

array([[0.90819445, 0.02864901, 0.54277663],
       [0.06056916, 0.35559868, 0.24248594]])

## Numpy Random Seed

In [29]:
np.random.seed(seed=0)
rand_arr4=np.random.randint(10,size=(3,5))
rand_arr4

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [30]:
rand_arr4.shape

(3, 5)

## Viewing Arrays and Matrices

In [31]:
np.unique(rand_arr4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a2

array([1, 2, 3, 4, 5])

In [33]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])