In [1]:
import numpy as np 

## Data Types and Attributes

In [2]:
# Numpy main Data Type is ndarray 
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
# 1-Dimensional Array 
'''
Dimension : 1-Dimensional
Shape : (1,5)
Names :  Arrays and Vector
'''
a2=np.array([1,2,3,4,5])
a2

array([1, 2, 3, 4, 5])

In [5]:
# 2-Dimensional Array 
'''
Dimension : 2-Dimensional 
Shape : (3,3)
Names : Arrays and Matrix
'''
a3=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# 3-Dimensional Array 
'''
Dimension : 3-Dimensional 
Shape : (2,3,2)
Names : Arrays and Matrix
'''
a4=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
print('a2 shape : ',end=' ')
print(a2.shape)

a2 shape :  (5,)


In [8]:
print('a3 shape : ',end=' ')
print(a3.shape)

a3 shape :  (3, 3)


In [9]:
print('a4 shape : ',end=' ')
print(a4.shape)

a4 shape :  (2, 3, 3)


In [10]:
a2.ndim , a3.ndim , a4.ndim

(1, 2, 3)

In [11]:
a2.dtype , a3.dtype , a4.dtype 

(dtype('int32'), dtype('int32'), dtype('int32'))

In [12]:
a2.size , a3.size , a4.size

(5, 9, 18)

In [13]:
type(a1) , type(a3) , type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Creating DataFrame from Numpy Arrays 
import pandas as pd 

df1=pd.DataFrame(a3)
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Creating Numpy Arrays 

In [15]:
sample_arr=np.array([1,2,3])
sample_arr

array([1, 2, 3])

In [16]:
sample_arr.dtype

dtype('int32')

In [17]:
one_arr=np.ones((2,3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
one_arr.dtype

dtype('float64')

In [19]:
type(one_arr)

numpy.ndarray

In [20]:
zero_arr=np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_arr=np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [22]:
rand_arr=np.random.randint(3,10,size=(2,3))
rand_arr

array([[6, 8, 5],
       [5, 3, 7]])

In [23]:
rand_arr.size 


6

In [24]:
rand_arr.shape

(2, 3)

In [25]:
rand_arr2=np.random.random((3,4))
rand_arr2

array([[0.64546146, 0.1616643 , 0.79668452, 0.25582574],
       [0.64517168, 0.33293716, 0.01423207, 0.78657748],
       [0.9534917 , 0.31706483, 0.48346545, 0.97661882]])

In [26]:
rand_arr2.shape

(3, 4)

In [27]:
rand_arr2.size

12

In [28]:
rand_arr3=np.random.rand(2,3)
rand_arr3

array([[0.34324608, 0.2657778 , 0.91286325],
       [0.91250667, 0.34404121, 0.44427068]])

## Numpy Random Seed

In [29]:
np.random.seed(seed=0)
rand_arr4=np.random.randint(10,size=(3,5))
rand_arr4

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [30]:
rand_arr4.shape

(3, 5)

## Viewing Arrays and Matrices

In [31]:
np.unique(rand_arr4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a2

array([1, 2, 3, 4, 5])

In [33]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a2[0]

1

In [36]:
a3[0]

array([1, 2, 3])

In [37]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a3[1]

array([4, 5, 6])

In [39]:
a4[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [40]:
a5=np.random.randint(10,size=(2,3,4,5))
a5

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [41]:
a5[:2,:2,:2,:2]

array([[[[6, 7],
         [5, 9]],

        [[3, 3],
         [9, 9]]],


       [[[4, 6],
         [4, 4]],

        [[0, 1],
         [0, 3]]]])

In [42]:
a5.shape , a5.ndim 

((2, 3, 4, 5), 4)

In [43]:

a5[1][2][0]

array([2, 3, 4, 1, 2])

In [44]:
# Getting the First 3 Element of the Inner most Element 
a5[:,:,:,:1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])

## Manipulating Arrays 

### Arithmetic 

In [45]:
a1

array([1, 2, 3])

In [50]:
one_arr1=np.ones(3)
one_arr1

array([1., 1., 1.])

In [51]:
a1+one_arr1

array([2., 3., 4.])

In [53]:
a1-one_arr1

array([0., 1., 2.])

In [54]:
a1*one_arr1

array([1., 2., 3.])

In [55]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a1*a3

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [60]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [74]:
# How to Make a2 Compactible with a4 for Arithmrtic Operation
#a2*a4
a1

array([1, 2, 3])

In [76]:
a4//a1

array([[[ 1,  1,  1],
        [ 4,  2,  2],
        [ 7,  4,  3]],

       [[10,  5,  4],
        [13,  7,  5],
        [16,  8,  6]]])

In [78]:
a3**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [79]:
np.square(a3)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [81]:
np.add(a1,a3)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [82]:
np.exp(a2)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [83]:
np.log(a2)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])