# NumPy Practice

In [5]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[1,2,3],
              [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.ndim , arr1.dtype , arr1.size , type(arr1)

(1, dtype('int32'), 3, numpy.ndarray)

In [10]:
# Attributes of 2-dimensional array
arr2.ndim , arr2.dtype , arr2.size , type(arr2)

(2, dtype('int32'), 6, numpy.ndarray)

In [11]:
# Attributes of 3-dimensional array
arr3.ndim , arr3.dtype , arr3.size , type(arr3)

(3, dtype('int32'), 18, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
data1=pd.DataFrame(arr2)
data1

0  1  2
0  1  2  3
1  4  5  6

In [15]:
# Create an array of shape (10, 2) with only ones
arr_ones=np.ones((10,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# Create an array of shape (7, 2, 3) of only zeros
arr_zeros=np.zeros((7,2,3))
arr_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
arr_range=np.arange(0,100,3)
arr_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_rand=np.random.randint(10,size=(7,2))
arr_rand

array([[4, 0],
       [4, 9],
       [5, 2],
       [5, 9],
       [9, 3],
       [1, 0],
       [0, 1]])

In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_rand1=np.random.random((3,5))
arr_rand1

array([[0.52184364, 0.14840873, 0.90398483, 0.33314991, 0.30589042],
       [0.10006967, 0.98425254, 0.95254029, 0.05416911, 0.6308819 ],
       [0.58830326, 0.48047532, 0.04071552, 0.19121416, 0.97347823]])

In [25]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_rand2=np.random.randint(10,size=(4,6))
arr_rand2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [28]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_rand3=np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
np.unique(arr_rand3)

array([1, 2, 3, 5, 7, 8, 9])

In [29]:
# Find the 0'th index of the latest array you created
arr_rand3[0]

array([2, 5, 8, 9, 9, 1, 9])

In [32]:
# Get the first 2 rows of latest array you created
arr_rand3[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
arr_rand3[:2,:2]

array([[2, 5],
       [7, 9]])

In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_rand4=np.random.randint(10,size=(3,5))
arr_ones1=np.ones((3,5))


In [40]:
# Add the two arrays together
arr_rand4+arr_ones1

array([[ 4.,  4.,  5.,  7.,  7.],
       [ 4.,  7.,  3.,  6.,  2.],
       [10.,  9.,  5.,  6.,  4.]])

In [41]:
# Create another array of ones of shape (5, 3)
arr_ones2=np.ones((5,3))
arr_ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# Try add the array of ones and the other most recent array together
arr_rec1=arr_ones1+arr_ones2.T

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [44]:
# Create another array of ones of shape (3, 5)
arr_ones3=np.ones((3,5))

In [46]:
# Subtract the new array of ones from the other most recent array
arr_ones2-arr_ones3.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
# Multiply the ones array with the latest array
arr_ones2*arr_ones3.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Take the latest array to the power of 2 using '**'


In [25]:
# Do the same thing with np.square()


In [26]:
# Find the mean of the latest array using np.mean()


In [27]:
# Find the maximum of the latest array using np.max()


In [28]:
# Find the minimum of the latest array using np.min()


In [29]:
# Find the standard deviation of the latest array


In [30]:
# Find the variance of the latest array


In [31]:
# Reshape the latest array to (3, 5, 1)


In [32]:
# Transpose the latest array


What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [34]:
# Perform a dot product on the two newest arrays you created


In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [39]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='


In [41]:
# Find which elements of the first array are greater than 7


In [42]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
